### ISSUE TITLE
[FIXED] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [Hakkin/ttaverify#1]
Dear Hakkin,
Could you be so kind to generate ```.exe``` for the rest of us who are merely users w/o compiler?

**Comment by Hakkin** [comment]
Hi, I've added 32 and 64bit binaries to the releases section, you can try them here: https://github.com/Hakkin/ttaverify/releases/tag/ff9e926
Let me know if they work for you.

**Comment by sergeevabc** [comment]
Thank you, Hakkin, x64 works perfectly fine. Glad to see wildcard ```*.tta``` is supported.
Could you tell a few words about algorithm and cases when one needs to verify his lossless library?

**Comment by Hakkin** [comment]
I originally made this because the hard drive that I stored most of my music collection on had started to fail, and I found that most TTA decoders (such as the one in foobar2000 and even the reference decoder on the TTA website) did not report any errors when there was corruption in the files.

The program is simply reading the header, seek table and individual audio frames, each of which have their own CRC, and comparing it to the data in the file. If any of them do not match, it will return an error and tell you which part of the file is corrupt (corrupt header and seek tables may be fixable, since they are relatively short and contain generally standard values).

**Comment by sergeevabc** [comment]
Lost data myself for a few times, helped others to recover, so I could imagine your pain, Hakkin.
How comes you ended up with TTA over other lossless formats and do you still use it?

**Comment by sergeevabc** [comment]
How comes you ended up with TTA instead of other lossless formats and do you still use it?

**Comment by Hakkin** [comment]
I mostly used it because it was a somewhat "de facto" format is a lot of Japanese and Chinese music communities, I mostly store my own CD rips in FLAC now, though I still think TTA as a format is fine.
